### ISSUE TITLE
Pull UploadSets from sufia-core down to curation_concerns

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#145]
Note: In Sufia, UploadSets are called Batches.  For clarity, we're changing that name.

Per the [code shredding halftime review](https://docs.google.com/document/d/1XWW5u2qflcpqAZDf0dtDYBD22Qqkd7L5rEQuisHvgX4/edit#heading=h.9yg4m11beddd).

This contradicts ~~#45~~ and ~~projecthydra-labs/sufia-core#7~~ which assumed sufia-core and sufia-ir would be pulled apart into separate gems. 

___TODO:___ Reciprocal issue in sufia-core: projecthydra-labs/sufia-core#76

**Comment by mjgiarlo** [comment]
Consider renaming Batches to UploadSets for clarity.

**Comment by flyingzumwalt** [comment]
+1 on renaming Batches to UploadSets.  This prevents confusion with other uses of the term "batch" like Hydra::Collections::Controller::AcceptsBatches

**Comment by flyingzumwalt** [comment]
Clarifying what to pull in from Sufia and what not to pull in
* _DO_ Track UploadSet when uploading multiple files, regardless of whether using Work-first or File-first workflow
* _DO_ continue (as sufia does) to store this info in SQL database instead of Fedora
* Implement UploadSetController based on Sufia's BatchController
* _DON'T_ pull in batch stuff from Sufia GenericFileActor
* _DON'T_ pull in BatchEditsController.  That has nothing to do with Upload Sets

**Comment by flyingzumwalt** [comment]
@mjgiarlo does my previous comment gel with your understanding of what I should do for this ticket?

**Comment by mjgiarlo** [comment]
@flyingzumwalt That seems right to me, though Sufia does store batch-related stuff in Fedora and not in the DB. The other four are :+1:

**Comment by flyingzumwalt** [comment]
@jpstroop um.. curation_concerns doesn't have multi-file uploads.  Without that, this functionality is irrelevant.  Do you want to add multi-file uploads as a feature for v0.2 or do you want to postpone adding UploadSets until 0.3?

Note: adding multi-file uploads then brings up the question of whether to pull in browse-everything and local-ingest.  Since those are both included in sufia-core's upload views right now, it might actually be easier to add them (straight copy & paste from sufia-core) rather than excluding them.

**Comment by jpstroop** [comment]
Hmm...missed that somehow, but we're sunk without multi-file uploads, so yes, I think that code should come down.

As to v0.2 or v0.later, the goal of this milestone was to finish code shredding so that work could begin on sufia-core, so I think it needs to happen in v0.2 (though I haven't looked at what all is involved yet). The cut and paste approach (adding browse-everything and local-ingest) seems like the right way to go as it sounds like that's the path of least resistance. We can always refine later.

**Comment by mjgiarlo** [comment]
Sounds good to me, too.
