### ISSUE TITLE
Refactor Pending and Commented Service Specs

### ISSUE THREAD

**Issue by jpstroop** [projecthydra-labs/curation_concerns#46]
* [x] spec/services/create_derivatives_service_spec.rb:  _(depends on projecthydra-labs/hydra-works#132)_
 * [x] spec/services/characterization_service_spec.rb: Fixed in #51

**Comment by kevinreiss** [comment]
Most of the functionality tested in create_derivatives_service_spec should be moved and tested within Hydra::Works in https://github.com/projecthydra-labs/hydra-works/issues/152.

**Comment by jpstroop** [comment]
@kevinreiss @tampakis (or anyone else) projecthydra-labs/hydra-works#132 is closed, not sure of the status of  projecthydra-labs/hydra-works#152. Can this proceed? It's the only real issue left on v0.1 milestone.

**Comment by kevinreiss** [comment]
Okay @jpstroop. I'll pick this back this afternoon.

**Comment by kevinreiss** [comment]
@jpstroop @tampakis @mjgiarlo should both sets of tests (thumbnail and a/v transcoding) in the existing create_derivatives_service_spec.rb be migrated to hydra::works?

**Comment by mjgiarlo** [comment]
@kevinreiss I'm inclined to say they should if that's where the code they test lives.

**Comment by jpstroop** [comment]
Those do sound like things Hydra::Works should be doing for us, and we wouldn't want to test Hydra::Works here, so I think so (without looking closely).

**Comment by tampakis** [comment]
We can remove the create_derivative_spec once https://github.com/projecthydra-labs/hydra-works/pull/183 is merged.

**Comment by mjgiarlo** [comment]
https://github.com/projecthydra-labs/hydra-works/pull/183 has been merged. This is now unblocked.

**Comment by mjgiarlo** [comment]
Assigning to @kevinreiss.  (Thanks, @tampakis!)

**Comment by kevinreiss** [comment]
@mjgiarlo I think all the specs dealing with [thumbnail generation](https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/services/create_derivatives_service_spec.rb#L16-L83) can be deleted since they have been directly moved over to [hydra-works](https://github.com/projecthydra-labs/hydra-works/blob/master/spec/hydra/works/services/persist_derivatives_spec.rb#L5-L92). Is there also general agreement with @tampakis that the other block of specs related to [a/v transcoding]( https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/services/create_derivatives_service_spec.rb#L85-L169) can also be removed?

**Comment by mjgiarlo** [comment]
I'm on the fence about this, @kevinreiss. I hate to lose test coverage, and I know some Sufia users depend upon transcoding (like the WGBH crew). Where should these tests live? Wondering what @tampakis, @jpstroop, @jcoyne, @terrellt, and others have in mind.

**Comment by kevinreiss** [comment]
Okay @mjgiarlo. Let's see what others think is appropriate for this gem. If we want to keep the test coverage for these should they be a part of sufia core? Or are they a concern of local application test suites?

If we do want to keep them here I think we need to implement  ```makes_derivatives``` from ```Hydra::Derivatives``` within a concern for GenericFile specifying the requested transcoding related derivative types from [sufia](https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/generic_file/derivatives.rb). Or at least construct the test to implement that method and configure the derivatives we ant to test.

**Comment by jpstroop** [comment]
Unless I'm missing something, to me this is testing the [integration](https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/models/concerns/generic_file/derivatives.rb) of Hydra::Derivatives into Hydra::Works and the specs in curation_concerns that @kevinreiss is talking about are testing a [relatively simple service](https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/services/curation_concerns/create_derivatives_service.rb#L5-L7), so I agree that they should go, or at least should be replaced with a lighter-weight integration test.

Aside: I'm wondering, do we need [this include](https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/services/curation_concerns/create_derivatives_service.rb#L3), since it's already included in `Hydra::Works::GenericFile::Derivatives`?

**Comment by tampakis** [comment]
Do we actually gain anything by having a CreateDerivatives service that we don't already have by calling `generic_file.create_derivatives`?

@kevinreiss and I decided that we'll implement the a/v derivatives in CC and keep the specs for now. We can decide later if those should live in Sufia instead of CC.

**Comment by mjgiarlo** [comment]
:+1: to that course of action. And no, I don't think the service is useful anymore. :clap: @tampakis @jpstroop @kevinreiss

**Comment by mjgiarlo** [comment]
@kevinreiss @tampakis @jpstroop Now that #150 is merged, can we mark this as complete, or move it over to the next milestone?

**Comment by tampakis** [comment]
Since the directly_contains syntax isn't used to specify A/V derivatives in curation concerns, these [A/V specs](https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/models/curation_concerns/generic_file/derivatives_spec.rb#L40-L75) should be removed.

These two specs about uploading A/V files in a [derivative format](https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/models/curation_concerns/generic_file/derivatives_spec.rb#L77-L109) definitely don't work as specified in the test (attach the original file as the derivative without going through the processor), but since the persist_derivative service in CC stores to the [filesystem](https://github.com/projecthydra-labs/curation_concerns/commit/f462b3c6425462612ca6fc4142ae75e1334ebbec), I'm thinking that the we should just remove those specs as well.

**Comment by mjgiarlo** [comment]
Seems reasonable to me, @tampakis. This touches on work you've done recently and in the past, @jcoyne, so I defer to you ultimately.

**Comment by flyingzumwalt** [comment]
We can close this ticket once #238 is merged.

**Comment by kevinreiss** [comment]
Closing.
