### ISSUE TITLE
Missing helper link_to_select_collection

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#83]
https://github.com/projecthydra-labs/curation_concerns/blob/10f702b5a212cd07273e81d64be429dc396dc9c6/app/views/catalog/_action_menu_partials/_default.html.erb#L22

**Comment by jcoyne** [comment]
Looks like it's originally from here: https://github.com/projecthydra-labs/worthwhile/blob/b89d24d82904633e040468ce0d57a7fa7b9cbbb6/app/helpers/worthwhile/collections_helper.rb#L10

**Comment by flyingzumwalt** [comment]
I would pull it in for now.  When we set up curation_concerns, we started with a fork of worthwhile and then removed a bunch of stuff.  We removed everything related to collections because we want to use Sufia's implementation of Collections (there was nothing especially worthwhile about worthwhile's implementation of Collections).  *However*, this specific helper method does something useful, it's used in the views for GenericWork (and other work types), and it should be compatible with Sufia's implementation of Collections.
